name: Nightly Build

on:
  schedule:
    - cron: '0 5 * * *'  # Runs every day at 5:00 AM UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.10" ]
        include:
          - os: ubuntu-latest
            firmware_name: FIRMWARE.IMG
            boot_name: BOOT.BIN
            tos_name: SIDECART.TOS
    steps:  
    - name: Checkout the code
      uses: actions/checkout@v3
  
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install AtariST Toolkit Docker image
      run: curl -sL https://github.com/sidecartridge/atarist-toolkit-docker/releases/download/v1.0.0/install_atarist_toolkit_docker.sh | bash

    - name: Run - remove interactive
      run: sed -i 's/-it//' /usr/local/bin/stcmd

    - name: Run build and publish
      run: ./build.sh ${GITHUB_WORKSPACE} release

    - name: Get current date
      id: build
      run: echo "::set-output name=date::$(date -u +"%Y-%m-%d %H:%M:%S UTC")"

    - name: Get version from version.txt
      run: echo "RELEASE_VERSION=$(cat version.txt)" >> $GITHUB_ENV

    - name: Upload the binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/${{ matrix.firmware_name }}
        asset_name: ${{ matrix.firmware_name }}
        tag: nightly
        release_name: Nightly Build - ${{ env.RELEASE_VERSION }}
        body: |
          **Disclaimer:** This is an automated nightly build generated on a daily basis. It may contain unstable or untested changes and is not guaranteed to work. Use at your own risk.

          **Release Notes:**
          - Build Date: ${{ steps.build.outputs.date }}
          - Version: ${{ env.RELEASE_VERSION }}

        file_glob: true
        overwrite: true
        prerelease: true
    - name: Upload the trimmed ROM image file
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/${{ matrix.boot_name }}
        asset_name: ${{ matrix.boot_name }}
        tag: nightly
        release_name: Nightly Build - ${{ env.RELEASE_VERSION }}
        overwrite: true
        prerelease: true
    - name: Upload the TOS file
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/${{ matrix.tos_name }}
        asset_name: ${{ matrix.tos_name }}
        tag: nightly
        release_name: Nightly Build - ${{ env.RELEASE_VERSION }}
        overwrite: true
        prerelease: true
